name: Publish to Production

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: Ubuntu-Latest
    environment:
      name: Production
      url: https://quippy.ink

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          api_location: ""
          app_location: "/public"
          output_location: ""
          skip_api_build: true
          skip_app_build: true
