name: Publish to Azure Static Web Apps

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: https://quippy.ink

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        id: publish-to-azure-swa
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_GRASS_0D9B95103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          api_location: ""
          app_location: "/public"
          output_location: "/public"
          skip_api_build: true
